[server]
headless = true
port=8501
enableCORS=false
runOnSave = true
enableXsrfProtection = true

[theme]
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"

[client]
showErrorDetails = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = true
